name: Prettier Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.1.0

      - name: Change directory to frontend
        run: cd ts-frontend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./ts-frontend

      - name: Run Prettier for frontend
        run: npm run prettier:github-action
        working-directory: ./ts-frontend
        continue-on-error: false

      - name: Check Prettier formatting for frontend
        id: prettier-status-frontend
        run: echo "::set-output name=prettier-status-frontend::$(npm run
          prettier:github-action || echo 'failed')"

      - name: Change directory to ts-backend
        run: cd ../backend/ts-backend
        working-directory: ./ts-frontend

      - name: Install ts-backend dependencies
        run: npm ci
        working-directory: ./backend/ts-backend

      - name: Run Prettier for ts-backend
        run: npm run prettier:github-action
        working-directory: ./backend/ts-backend
        continue-on-error: false

      - name: Check Prettier formatting for ts-backend
        id: prettier-status-ts-backend
        run: echo "::set-output name=prettier-status-backend::$(npm run
          prettier:github-action || echo 'failed')"

      - name: Change directory to ws
        run: cd ../ws
        working-directory: ./backend/ts-backend

      - name: Install ws-backend dependencies
        run: npm ci
        working-directory: ./backend/ws

      - name: Run Prettier for ws-backend
        run: npm run prettier:github-action
        working-directory: ./backend/ws
        continue-on-error: false

      - name: Check Prettier formatting for ws-backend
        id: prettier-status-backend
        run: echo "::set-output name=prettier-status-ws-backend::$(npm run
          prettier:github-action || echo 'failed')"
