name: Prettier Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.1.0

      - name: Change directory to frontend
        run: cd ts-frontend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./ts-frontend

      - name: Run Prettier for frontend
        run: npm run prettier:github-action
        working-directory: ./ts-frontend
        continue-on-error: false

      - name: Check Prettier formatting for frontend
        id: prettier-status-frontend
        run:
          echo "::set-output name=prettier-status-frontend::$(npm run
          prettier:github-action || echo 'failed')"

      - name: Change directory to backend
        run: cd ../ts-backend
        working-directory: ./ts-frontend

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./ts-backend

      - name: Run Prettier for backend
        run: npm run prettier:github-action
        working-directory: ./ts-backend
        continue-on-error: false

      - name: Check Prettier formatting for backend
        id: prettier-status-backend
        run:
          echo "::set-output name=prettier-status-backend::$(npm run
          prettier:github-action || echo 'failed')"
